#!/bin/sh

# LLVM Configuration and build
cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="lldb;clang;libclc;lld;mlir" -DLLVM_TARGETS_TO_BUILD="AArch64;X86;NVPTX;AMDGPU;RISCV" -DCMAKE_INSTALL_PREFIX="${HOME}/localinstall/llvm_dbg" -DBUILD_SHARED_LIBS=ON -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Debug -DMLIR_INCLADE_TESTS=ON -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON -DLLVM_REVERSE_ITERATION=ON -DLLVM_ENABLE_ZSTD=OFF -DCLANG_ENABLE_CIR=ON

#cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="lldb;clang;libclc;lld;mlir" -DLLVM_TARGETS_TO_BUILD="AArch64;X86;NVPTX;AMDGPU;RISCV" -DCMAKE_INSTALL_PREFIX="${HOME}/localinstall/llvm_rel" -DBUILD_SHARED_LIBS=ON -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DMLIR_INCLADE_TESTS=ON -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON -DLLVM_REVERSE_ITERATION=ON -DLLVM_ENABLE_ZSTD=OFF -DCLANG_ENABLE_CIR=ON